"""Initial migration

Revision ID: 8191e309a223
Revises: 
Create Date: 2025-06-26 11:20:52.468957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8191e309a223'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='上传的文件名'),
    sa.Column('status', sa.String(length=51), nullable=False, comment='任务状态'),
    sa.Column('result', sa.JSON(), nullable=True, comment='任务处理结果'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='任务失败的错误信息'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
